import {
  IconAlertCircle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconLoader2,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconUser,
  IconX,
  IconEdit,
  IconCalendar,
  IconTag,
  IconLogout,
  IconHome,
  IconList,
  IconLayoutKanban,
  IconInbox,
  IconSearch,
  IconEye,
  IconEyeOff,
  IconBrandGoogle,
  IconBrandApple,
  IconPaperclip,
  IconImageInPicture,
  IconLayoutGrid,
  IconBell,
  IconRefresh,
  IconCheckbox,
  IconStar,
  IconMessageCircle,
  IconArrowLeft,
  IconClock,
  IconLoader,
  IconCircle,
  type Icon as TablerIconType,
} from "@tabler/icons-react";

export type Icon = TablerIconType;

export const Icons = {
  logo: IconCommand,
  close: IconX,
  spinner: IconLoader2,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  edit: IconEdit,
  post: IconFileText,
  page: IconFile,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertCircle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  calendar: IconCalendar,
  tag: IconTag,
  logout: IconLogout,
  home: IconHome,
  list: IconList,
  kanban: IconLayoutKanban,
  inbox: IconInbox,
  search: IconSearch,
  plus: IconPlus,
  check: IconCheck,
  eye: IconEye,
  eyeOff: IconEyeOff,
  google: IconBrandGoogle,
  apple: IconBrandApple,
  paperclip: IconPaperclip,
  image: IconImageInPicture,
  layoutGrid: IconLayoutGrid,
  x: IconX,
  bell: IconBell,
  refresh: IconRefresh,
  checkSquare: IconCheckbox,
  star: IconStar,
  messageCircle: IconMessageCircle,
  arrowLeft: IconArrowLeft,
  clock: IconClock,
  loader: IconLoader,
  circle: IconCircle,
  moreVertical: IconDotsVertical,
  file: IconFile,
};
